AWSTemplateFormatVersion: "2010-09-09"
Description: "PX-Enterprise"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
        default: Basic Settings
      Parameters:
        - KubeClusterName
        - SecretType
      - Label:
        default: Storage Settings
      Parameters:
        - DiskSpec
        - MaxStorageNodes
    ParameterLabels:
      KubeClusterName:
        default: "Clustername"
      DiskSpec:
        default: "Disk Spec"
      MaxStorageNodes:
        default: "Max. storage nodes"
Parameters:
  KubeClusterName:
    Description: "Portworx Cluster name"
    Type: String
  SecretType:
    Description: "Secret store (defaults to none)"
    Type: String
    AllowedValues: ["none", "aws-kms", "k8s" ]
    Default: "none"
  DiskSpec:
    Type: String
    Description: "Disk spec in the format of (type=gp2,size=150) or (type=io1,size=150,iops=10000). use semi-colon to delimit multiple disks"
  MaxStorageNodes:
    Description: "[OPTIONAL] Maximum storage nodes per availability zone"
    Type: Number
Resources:
  # This resource deploys the kubernetes service catalog from it's helm chart.
  #
  # using !GetAtt you can fetch Name (release name) and Namespace, as well as all of the created resources, who's keys
  # are the resource type + an index for the case where a chart creates more than 1 of a Kind (eg. ConfigMap0 fetches
  # the 1st ConfigMap created)
  HelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref KubeClusterName
      # If the chart is not in the stable repo then supply a repo url
      # RepoUrl: https://svc-catalog-charts.storage.googleapis.com
      # namespace is optional, in most cases it's best to leave this out so that a namespace is dynamically generated.
      # If namespace does not exist it will be created
      #
      # Namespace: example-ns
      #
      # supply chart name in "repo-name/chart-name" or "https://repo-hostname/repo-path/chart-package.tgz"
      Chart: https://github.com/portworx/eks-helm/blob/master/chart-package.tgz
      # Name can be specified, if not helm will generate one
      Name: my-release
      # Version can be specified, if not latest will be used
      # Version: 2.6.0
      # Custom values can optionally be specified
      # Values:
      # If there are a lot of values, or they contain ambiguous types (eg, enable: "true" or count: "1") then values can
      # be passed as yaml enclosed in a string literal
      ValueYaml: |
        # Please uncomment and specify values for these options as per your requirements.
        kvdb:                                  # The KVDB endpoint. Should be in the format etcd:http://<your-kvdb-endpoint>:2379.
                                               # If there are multiple endpoints they need to be ";" seperated.
                                               # the default value is empty since it requires to be explicity set using either the --set option of -f values.yaml.
        clusterName: !Ref KubeClusterName      # This is the default. please change it to your cluster name.

        storage:
          usefileSystemDrive: false             # true/false Instructs PX to use an unmounted Drive even if it has a filesystem.
          usedrivesAndPartitions: false         # Defaults to false. Change to true and PX will use unmounted drives and partitions.
          drives: !Ref DiskSpec                # NOTE: This is a ";" seperated list of drives. For eg: "/dev/sda;/dev/sdb;/dev/sdc" Defaults to use -A switch.
          journalDevice: none
          metadataSize: 0

        network:
          dataInterface: none                   # Name of the interface <ethX>
          managementInterface: none             # Name of the interface <ethX>

        secretType: !Ref SecretType           # Defaults to None, but can be aws-kms/vault/k8s/kvdb
        envVars: none                         # NOTE: This is a ";" seperated list of environment variables. For eg: MYENV1=myvalue1;MYENV2=myvalue2
        advOpts: none

        storkVersion: 2.4.1

        customRegistryURL:
        registrySecret:
        imagePullSecrets:

        csi: false                            # Enable CSI

        internalKVDB: true                   # internal KVDB

        etcd:
          secret: none                       # Secret name where the username, password and CA cert for ETCD authentication is stored
        imageVersion: 2.0.6                   # Version of the PX Image.
        changePortRange: false               #change start range to 17000

        serviceAccount:
          hook:
            create: true
            name:
