# Please uncomment and specify values for these options as per your requirements.

# This is the marketplace subscribed product: PX-ENTERPRISE or PX-ENTERPRISE+DR
awsProduct: "PX-ENTERPRISE"         #This is the default.

clusterName: mycluster              # This is the default. please change it to your cluster name.

storage:
  usefileSystemDrive: false         # true/false Instructs PX to use an unmounted Drive even if it has a filesystem.
  usedrivesAndPartitions: false     # Defaults to false. Change to true and PX will use unmounted drives and partitions.
  drives: none                      # NOTE: This is a ";" seperated list of drives. For eg: "/dev/sda;/dev/sdb;/dev/sdc" Defaults to use -A switch.
                                    # To have drives automatically created specify the drive spec. For Eg: "type=gp2,size=150" or "type=io1,size=100,iops=2000"
  journalDevice: none
  metadataSize: 0

network:
  dataInterface: none               # Name of the interface <ethX>
  managementInterface: none         # Name of the interface <ethX>

secretType: none                    # Defaults to None, but can be aws-kms/k8s
envVars: none                       # NOTE: This is a ";" seperated list of environment variables. For eg: MYENV1=myvalue1;MYENV2=myvalue2
advOpts: none

csi: false                          # Enable CSI

internalKVDB: true                  # internal KVDB

imageVersion: 2.5.6                 # Version of the PX Image.
storkVersion: 2.4.4                 # Version of the Stork Image
autopilotVersion: 1.2.1             # Version of the Autopilot Image.
operatorVersion: 1.3.4              # Version of the PX Operator Image.

customRegistryURL:
registrySecret:

serviceAccount:
  hook:
    create: true
    name:
