apiVersion: core.libopenstorage.org/v1alpha1
kind: StorageCluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: kube-system
  annotations:
    portworx.com/install-source: helm/{{.Release.Service}}-r{{.Release.Revision}}
    portworx.com/helm-vars: chart="{{.Chart.Name}}-{{.Chart.Version}}"{{range $k, $v := .Values }}{{if $v}},{{ $k }}="{{ $v }}" {{end}}{{end}}
spec:
  image: portworx/oci-monitor:{{.Values.imageVersion}}
  imagePullPolicy: Always
  kvdb:
    internal: true
  {{- if eq .Values.drives "none" }}
  storage:
    useAllWithPartitions: {{ .Values.usedrivesAndPartitions }}
    forceUseDisks: {{ .Values.usefileSystemDrive }}
    journalDevice: auto
    kvdbDevice: type=gp2,size=150
    {{- if ne .Values.maxStorageNodesPerZone  "none" }}
    maxStorageNodesPerZone: {{ .Values.maxStorageNodesPerZone }}
    {{- end }}
  {{- else }}
  cloudStorage:
    deviceSpecs:
    {{- $driveNames := .Values.drives | split ";" }}
    {{- range $index, $name := $driveNames }}
    - {{ $name }}
    {{- end }}
    journalDevice: auto
    kvdbDeviceSpec: type=gp2,size=150
    {{- if ne .Values.maxStorageNodesPerZone  "none" }}
    maxStorageNodesPerZone: {{ .Values.maxStorageNodesPerZone }}
    {{- end }}
  {{- end }}
  {{- if (ne .Values.dataInterface "none") or (ne .Values.managementInterface "none") }}
  network:
    {{- if ne .Values.dataInterface "none" }}
    dataInterface: {{ .Values.dataInterface }}
    {{- end }}
    {{- if ne .Values.managementInterface "none" }}
    mgmtInterface: {{ .Values.managementInterface }}
  {{- end }}
  secretsProvider: k8s
  stork:
    enabled: true
    image: openstorage/stork:{{.Values.storkVersion}}
  autopilot:
    enabled: true
    image: portworx/autopilot:{{.Values.autopilotVersion}}
    providers:
    - name: default
      type: prometheus
      params:
        url: http://prometheus:9090
  {{- if .Values.csi }}
  featureGates:
    CSI: "true"
  {{- end }}
