{{- $namespace := .Values.namespace | default "kube-system" }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $namespace }}
  name: px-osb
type: Opaque
stringData:
  product-id: {{ template "px.getProductID" .}}
